cicd pipeline done

diff --git a/bin/cfn/cicd-deploy b/bin/cfn/cicd-deploy
--- a/bin/cfn/cicd-deploy
+++ b/bin/cfn/cicd-deploy
@@ -1,12 +1,14 @@
 #! /usr/bin/bash
 
-set -e # stop execution if anything fails
+# set -e # stop execution if anything fails
 
 abs_template_filepath="$ABS_PATH/aws/cfn/cicd/template.yaml"
 TemplateFilePath=$(realpath --relative-base="$PWD" "$abs_template_filepath")
 
 abs_config_filepath="$ABS_PATH/aws/cfn/cicd/config.toml"
 ConfigFilePath=$(realpath --relative-base="$PWD" "$abs_config_filepath")
+
+PackagedPath="$ABS_PATH/tmp/packages-template.yaml"
 
 BUCKET=$(cfn-toml key deploy.bucket -t $ConfigFilePath)
 REGION=$(cfn-toml key deploy.region -t $ConfigFilePath)
@@ -15,12 +17,24 @@ PARAMETERS=$(cfn-toml params v2 -t $ConfigFilePath)
 
 cfn-lint $TemplateFilePath
 
+
+echo ">>> packaging CFN to S3 <<<"
+
+aws cloudformation package \
+  --template-file $TemplateFilePath \
+  --s3-bucket $BUCKET \
+  --s3-prefix cicd-package \
+  --region $REGION \
+  --output-template-file $PackagedPath
+
+echo ">>> Deploy CFN <<<"
+
 aws cloudformation deploy \
   --stack-name "$STACK_NAME" \
   --s3-bucket "$BUCKET" \
-  --s3-prefix cluster \
+  --s3-prefix cicd \
   --region $REGION \
-  --template-file $TemplateFilePath \
+  --template-file $PackagedPath \
   --no-execute-changeset \
   --tags group=cruddur-cicd \
   --parameter-overrides $PARAMETERS \
